spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/luckylogistics
    username: luckyvicky
    password: luckyvicky
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_schema: hubs
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql