server:
  port: 19094

spring:
  application:
    name: hub

  profiles:
    include:
      - datasource
      - eureka
      - zipkin

  jackson:
    time-zone: Asia/Seoul

  output:
    ansi:
      enabled: always

